### ISSUE TITLE
View text data in result

### ISSUE THREAD

**Issue by rahulptel** [LantaoYu/SeqGAN#16]
What modifications do we need to make in the code to see the text generated. I would like to see results of Obama speech generated, as mentioned in the paper along with the loss. Also, can you share the data used for training.

**Comment by LantaoYu** [comment]
Hi, we provide the more persuasive synthetic data experiments for demonstration in this repository. You may read the "Synthetic Data Experiments" section of this [paper](https://arxiv.org/pdf/1609.05473.pdf) for more details.

For running experiments in the real world data, the easiest way is to preprocess the text data into sequences of numbers and just use that as the real data file instead of generating one. Also change the evaluation methods.

The Obama dataset can be found [here](https://github.com/samim23/obama-rnn).
