### ISSUE TITLE
Monte-Carlo roll-out 

### ISSUE THREAD

**Issue by WangWenshan** [LantaoYu/SeqGAN#39]
Hi, 
Thank you for your job.
I have question that how to process variable sequences in MC rollout?
Thanks

**Comment by eduOS** [comment]
I am wondering what you meant by "to process variable sequences in MC rollout"?

**Comment by WangWenshan** [comment]
Sequences do not always have the same length. 
You can see Figure 1 in the paper (https://arxiv.org/abs/1612.00370)

**Comment by eduOS** [comment]
I think it is the same as that in generating the targets while training the decoder, since when you calculate the loss you will mask out the tokens from the end_token until the end of the sentence. The same applies to the roll-out, that is, when you work out the gan loss you will mask out the unnecessary tokens at the end of each sentence.

**Comment by WangWenshan** [comment]
Thanks
